### ISSUE TITLE
otegsub5.ttf invalid, unable to re-build

### ISSUE THREAD

**Issue by Jongware** [twardoch/test-fonts#2]
As its TTX dump shows, the font otegsub5.ttf is damaged beyond use:

...
<SubstLookupRecord index="23">
    <SequenceIndex value="29541"/>
    <LookupListIndex value="770"/>
</SubstLookupRecord>

-- the number of substitutionCount is a whopping 24 instead of the assumed 2 (guessing from the fea file), and the positions and lookup indices are way off. Physical inspection of the file shows that this table runs into the feature name list!

I attempted to re-build the font with the provided .fea file, but the test sequence

lookup test { sub a b' by c; } test;

does not produce a Contextual Substitution; the first 'a' is a lookbehind instead, and so it produces a Chaining Contextual Sub instead. Unfortunately, so does changing that line to

lookup test { sub a' b by c; } test;

as makeotf prefers a Type 6 subst over a Type 5 at any time:

"5.e. [GSUB LookupType 5] Contextual substitution
This LookupType is a functional subset of GSUB LookupType 6, chaining contextual substitution. Thus, all desired rules of this LookupType can be expressed in terms of chaining contextual substitution rules."

Is it possible to replace the current font with a valid otegsub5.ttf?

**Comment by twardoch** [comment]
I don't know. I made these fonts 15 years ago, in a much older version of AFDKO and TTX. I wouldn't expect them to be always valid today. They're a snapshot of the font technology of 2005 as much as they're tests for today's tech. :)

**Comment by twardoch** [comment]
I frankly don't really remember how I made these. But I think I did edit the .ttx files somehow and then compiled with fontTools 'ttx'. But yeah, 15 years :)

**Comment by twardoch** [comment]
So if a font is invalid, feel free to file a PR with a better one (both .ttx & .ttf) and I'll merge it. But I won't test it :)

**Comment by Jongware** [comment]
There you go. 30 minutes to fix, 2 hours to try & push it, 3 days to wait for a new computer so git finally works ...

**Comment by twardoch** [comment]
Thanks, merged!
